### ISSUE TITLE
Feedback on the function named  regarding logical issues.

### ISSUE THREAD

**Issue by hmu-youbai** [bioc/MethTargetedNGS#1]
![image](https://github.com/bioc/MethTargetedNGS/assets/78633949/a79a7d9b-5809-4f64-b904-66341354609c)

When using a 16-row by 4-column matrix, where the first eight rows are all "T" and the last eight rows are all "C", I obtain a methEntropy value of 0.43. However, the value given in the article is 0.1875. I noticed that there might be a logical issue in the function's code. Specifically, the loop for (k in (j+1):length(entropy_list)) and the line entropy_list <- entropy_list[-k] could lead to a situation where the index becomes smaller than the upper bound during the loop.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of Bioconductor, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
